name: 'Deploy'

on:
  push:
    branches:
    - 'master'

jobs:

  deploy:
    name: 'Deploy to Pages'
    runs-on: 'ubuntu-latest'

    steps:

    - name: 'Setup Node'
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: 'Checkout Code'
      uses: actions/checkout@v2

    - name: 'Install Dependencies'
      run: npm ci

    - name: 'Build Static Content'
      run: npx parcel build src/index.html --public-url /virtual-hugs/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
